In [1]:
#Imports
import pickle
import os
from pathlib import Path
from shared.utils import run_model, load_snapshot
from shared.plotting import plot_sankey
from energyscope.models import Model

# 2050 - Sans pointe

In [2]:
# 1. Définition des chemins absolus
_BASE_DIR = Path(r"C:\Users\julie\Desktop\EnergyScope-Quebec")
_MODEL_2050_DIR = _BASE_DIR / 'shared' / 'model'
_DATA_2050_DIR = _BASE_DIR / 'shared' / 'data'
_DATA_EUD_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'EUD'
_DATA_TECHS_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Techs'
_DATA_SHARES_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Shares'
_PROJECT_DIR = _BASE_DIR / 'projects' / 'peaks' / '02_Model'

# 2. Construction du modèle unique ordonné (2050 Carboneutre - Sans Pointes, Avec HP)
energyscope_2050 = Model([
    # --- FICHIERS DE BASE (Partagés) ---
    ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
    ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
    ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
    ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
    ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
    ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
    ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),

    # --- ÉLÉMENTS DE MODÉLISATION SUPPLÉMENTAIRES  ---
    ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
    ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),
    ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

    ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),

    # --- ÉLÉMENTS DE MODÉLISATION SUPPLÉMENTAIRES  ---

    #('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')), # Limite annuelle d'hydro
    #('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
    #('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),

    # --- DONNÉES ET SCRIPTS DE CONTEXTE ---
    # 1. Données spécifiques au scénario carboneutre (ex: co2_limit := 0;)
    #('dat', str(_PROJECT_DIR / 'carboneutre.dat')),
    #,
])

In [5]:
results_wo_peaks_2050 = run_model(energyscope_2050, apply_postprocessing=True)
plot_sankey(results_wo_peaks_2050)

Gurobi 12.0.3:

In [6]:
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_wo_peaks_2050.pkl')
os.makedirs(output_dir, exist_ok=True)

# Sauvegarde
with open(output_path, 'wb') as f:
    pickle.dump(results_wo_peaks_2050, f)

# 2050 - Sans pointe - Carboneutre

In [7]:
from pathlib import Path

# 1. Définition des chemins absolus
_BASE_DIR = Path(r"C:\Users\julie\Desktop\EnergyScope-Quebec")
_MODEL_2050_DIR = _BASE_DIR / 'shared' / 'model'
_DATA_2050_DIR = _BASE_DIR / 'shared' / 'data'
_DATA_EUD_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'EUD'
_DATA_TECHS_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Techs'
_DATA_SHARES_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Shares'
_PROJECT_DIR = _BASE_DIR / 'projects' / 'peaks' / '02_Model'

# 2. Construction du modèle unique ordonné (2050 Carboneutre - Sans Pointes, Avec HP)
energyscope_2050_carboneutre = Model([
    # --- 1. DÉCLARATIONS DES MODÈLES (Tous les .mod de base et extensions) ---
    ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
    ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
    ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
    ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
    ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
    ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
    ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),

    # --- 2. AJOUTS HP, SPLIT IMPORTS,  (Via des commandes 'let') ---
    ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
    ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),

    ('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')),
    ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

    ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),

    # --- 3. Carboneutre ---
    ('dat', str(_PROJECT_DIR / 'carboneutre.dat')),
])

In [8]:
results_wo_peaks_2050_carboneutre = run_model(energyscope_2050_carboneutre,apply_postprocessing=True)
plot_sankey(results_wo_peaks_2050_carboneutre)

Gurobi 12.0.3:

In [10]:
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_wo_peaks_2050_carboneutre.pkl')
os.makedirs(output_dir, exist_ok=True)

# Sauvegarde
with open(output_path, 'wb') as f:
    pickle.dump(results_wo_peaks_2050_carboneutre, f)

# 2050 - Sans pointe - Carboneutre - Plan HQ

In [16]:
from pathlib import Path

# 1. Définition des chemins absolus
_BASE_DIR = Path(r"C:\Users\julie\Desktop\EnergyScope-Quebec")
_MODEL_2050_DIR = _BASE_DIR / 'shared' / 'model'
_DATA_2050_DIR = _BASE_DIR / 'shared' / 'data'
_DATA_EUD_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'EUD'
_DATA_TECHS_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Techs'
_DATA_SHARES_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Shares'
_PROJECT_DIR = _BASE_DIR / 'projects' / 'peaks' / '02_Model'

# 2. Construction du modèle unique ordonné (2050 Carboneutre - Sans Pointes, Avec HP)
energyscope_2050_carboneutre_planHQ = Model([
    # --- 1. DÉCLARATIONS DES MODÈLES (Tous les .mod de base et extensions) ---
    ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
    ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
    ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
    ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
    ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
    ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
    ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),

    # --- 2. AJOUTS HP, SPLIT IMPORTS,  (Via des commandes 'let') ---
    ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
    ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),

    ('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')),
    ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

    ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),

    ('mod', str(_PROJECT_DIR / 'plan_action_HQ_2035.mod')),

    # --- 3. Carboneutre ---
    ('dat', str(_PROJECT_DIR / 'carboneutre.dat')),
])

In [17]:
results_wo_peaks_2050_carboneutre_planHQ = run_model(energyscope_2050_carboneutre_planHQ,apply_postprocessing=True)
plot_sankey(results_wo_peaks_2050_carboneutre_planHQ)

Gurobi 12.0.3:

In [18]:
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_wo_peaks_2050_carboneutre_planHQ.pkl')
os.makedirs(output_dir, exist_ok=True)

# Sauvegarde
with open(output_path, 'wb') as f:
    pickle.dump(results_wo_peaks_2050_carboneutre_planHQ, f)

# 2050 - Sans pointe - Carboneutre - Capture 0

In [19]:
from pathlib import Path

# 1. Définition des chemins absolus
_BASE_DIR = Path(r"C:\Users\julie\Desktop\EnergyScope-Quebec")
_MODEL_2050_DIR = _BASE_DIR / 'shared' / 'model'
_DATA_2050_DIR = _BASE_DIR / 'shared' / 'data'
_DATA_EUD_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'EUD'
_DATA_TECHS_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Techs'
_DATA_SHARES_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Shares'
_PROJECT_DIR = _BASE_DIR / 'projects' / 'peaks' / '02_Model'

# 2. Construction du modèle unique ordonné (2050 Carboneutre - Sans Pointes, Avec HP)
energyscope_2050_carboneutre_limite_CC = Model([
    # --- 1. DÉCLARATIONS DES MODÈLES (Tous les .mod de base et extensions) ---
    ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
    ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
    ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
    ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
    ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
    ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
    ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),

    # --- 2. AJOUTS HP, SPLIT IMPORTS,  (Via des commandes 'let') ---
    ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
    ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),

    ('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')),
    ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

    ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),

    # --- 3. Carboneutre ---
    ('dat', str(_PROJECT_DIR / 'carboneutre.dat')),

    ('mod', str(_PROJECT_DIR / 'capture_limite.mod')),
    ('dat', str(_PROJECT_DIR / 'capture_limite.dat')),
])

In [20]:
results_wo_peaks_2050_carboneutre_limite_CC = run_model(energyscope_2050_carboneutre_limite_CC,apply_postprocessing=True)
plot_sankey(results_wo_peaks_2050_carboneutre_limite_CC)

Gurobi 12.0.3:

In [21]:
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_wo_peaks_2050_carboneutre_limite_CC.pkl')
os.makedirs(output_dir, exist_ok=True)

# Sauvegarde
with open(output_path, 'wb') as f:
    pickle.dump(results_wo_peaks_2050_carboneutre_limite_CC, f)

# 2050 - Avec pointe - Carboneutre - Capture 0

In [37]:
from pathlib import Path

# 1. Définition des chemins absolus
_BASE_DIR = Path(r"C:\Users\julie\Desktop\EnergyScope-Quebec")
_MODEL_2050_DIR = _BASE_DIR / 'shared' / 'model'
_DATA_2050_DIR = _BASE_DIR / 'shared' / 'data'
_DATA_EUD_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'EUD'
_DATA_TECHS_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Techs'
_DATA_SHARES_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Shares'
_PROJECT_DIR = _BASE_DIR / 'projects' / 'peaks' / '02_Model'

# 2. Construction du modèle unique ordonné (2050 Carboneutre - Avec Pointes ET Limite Capture CO2)
energyscope_2050_carboneutre_peaks_limite_CC = Model([
    # --- 1. DÉCLARATIONS DES MODÈLES (Tous les .mod de base et extensions) ---
    ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
    ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
    ('mod', str(_PROJECT_DIR / 'peaks_extra.mod')), # <-- Ajouté pour la gestion des pointes
    ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
    ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
    ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
    ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
    ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),

    # --- 2. AJOUTS HP, SPLIT IMPORTS,  (Via des commandes 'let') ---
    ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
    ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),

    ('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')),
    ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

    ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),

    # --- 3. Carboneutre ---
    ('dat', str(_PROJECT_DIR / 'carboneutre.dat')),

    # --- 4. Pointes ---
    ('dat', str(_PROJECT_DIR / 'peaks_2_2050.dat')),   # <-- Ajouté pour les données de pointe
    ('dat', str(_PROJECT_DIR / 'peaks_2050_cpt.dat')), # <-- Ajouté pour les données de pointe

    # --- 5. Limites de capture de CO2 ---
    ('mod', str(_PROJECT_DIR / 'capture_limite.mod')),
    ('dat', str(_PROJECT_DIR / 'capture_limite.dat')),
])

In [38]:
results_peaks_2050_carboneutre_limite_CC = run_model(energyscope_2050_carboneutre_peaks_limite_CC,apply_postprocessing=True)
plot_sankey(results_peaks_2050_carboneutre_limite_CC)

Gurobi 12.0.3:

In [40]:
results_peaks_2050_carboneutre_limite_CC.variables['F_Mult_t']

                    F_Mult_t  Run
index0      index1
ACETIC_ACID 1            0.0    0
            2            0.0    0
            3            0.0    0
            4            0.0    0
            5            0.0    0
...                      ...  ...
XYLENE      10           0.0    0
            11           0.0    0
            12           0.0    0
            13           0.0    0
            14           0.0    0

[10892 rows x 2 columns]

In [41]:
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_peaks_2050_carboneutre_limite_CC.pkl')
os.makedirs(output_dir, exist_ok=True)

# Sauvegarde
with open(output_path, 'wb') as f:
    pickle.dump(results_peaks_2050_carboneutre_limite_CC, f)

# 2050 - Sans pointe - Carboneutre - Plan HQ - Capture 0

In [29]:
from pathlib import Path

# 1. Définition des chemins absolus
_BASE_DIR = Path(r"C:\Users\julie\Desktop\EnergyScope-Quebec")
_MODEL_2050_DIR = _BASE_DIR / 'shared' / 'model'
_DATA_2050_DIR = _BASE_DIR / 'shared' / 'data'
_DATA_EUD_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'EUD'
_DATA_TECHS_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Techs'
_DATA_SHARES_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Shares'
_PROJECT_DIR = _BASE_DIR / 'projects' / 'peaks' / '02_Model'

# 2. Construction du modèle unique ordonné (2050 Carboneutre - Avec Pointes ET Limite Capture CO2)
energyscope_2050_carboneutre_wo_peaks_limite_CC_HQ = Model([
    # --- 1. DÉCLARATIONS DES MODÈLES (Tous les .mod de base et extensions) ---
    ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
    ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
    ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
    ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
    ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
    ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
    ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),
    ('mod', str(_PROJECT_DIR / 'plan_action_HQ_2035.mod')),


    # --- 2. AJOUTS HP, SPLIT IMPORTS,  (Via des commandes 'let') ---
    ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
    ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),

    ('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')),
    ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

    ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),

    # --- 3. Carboneutre ---
    ('dat', str(_PROJECT_DIR / 'carboneutre.dat')),

    # --- 5. Limites de capture de CO2 ---
    ('mod', str(_PROJECT_DIR / 'capture_limite.mod')),
    ('dat', str(_PROJECT_DIR / 'capture_limite.dat')),
])

In [30]:
results_wo_peaks_2050_carboneutre_limite_CC_HQ = run_model(energyscope_2050_carboneutre_wo_peaks_limite_CC_HQ,apply_postprocessing=True)
plot_sankey(results_wo_peaks_2050_carboneutre_limite_CC_HQ)

Gurobi 12.0.3:

In [31]:
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_wo_peaks_2050_carboneutre_limite_CC_HQ.pkl')
os.makedirs(output_dir, exist_ok=True)

# Sauvegarde
with open(output_path, 'wb') as f:
    pickle.dump(results_wo_peaks_2050_carboneutre_limite_CC_HQ, f)

# 2050 - Avec pointe - Carboneutre

In [13]:
from pathlib import Path

# 1. Définition des chemins absolus
_BASE_DIR = Path(r"C:\Users\julie\Desktop\EnergyScope-Quebec")
_MODEL_2050_DIR = _BASE_DIR / 'shared' / 'model'
_DATA_2050_SCENARIO = _BASE_DIR / 'shared' / 'scenarios'
_DATA_2050_DIR = _BASE_DIR / 'shared' / 'data'
_DATA_EUD_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'EUD'
_DATA_TECHS_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Techs'
_DATA_SHARES_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Shares'
_PROJECT_DIR = _BASE_DIR / 'projects' / 'peaks' / '02_Model'

# 2. Construction du modèle unique ordonné (2050 Carboneutre - Sans Pointes, Avec HP)
energyscope_2050_carboneutre_peaks = Model([
    # --- 1. DÉCLARATIONS DES MODÈLES (Tous les .mod de base et extensions) ---
    ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
    ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
    ('mod', str(_PROJECT_DIR / 'peaks_extra.mod')),
    ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
    ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
    ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
    ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
    ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),

    # --- 2. AJOUTS HP, SPLIT IMPORTS,  (Via des commandes 'let') ---

    ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
    ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),

    ('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')),
    ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

    ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),
    #('mod', str(_PROJECT_DIR / 'plan_action_HQ_2035.mod')),

    # --- 3. Carboneutre ---
    ('dat', str(_PROJECT_DIR / 'carboneutre.dat')),

    # --- 4. Pointes ---
    ('dat', str(_PROJECT_DIR / 'peaks_2_2050.dat')),
    ('dat', str(_PROJECT_DIR / 'peaks_2050_cpt.dat')),

])

In [14]:
results_peaks_2050_carboneutre = run_model(energyscope_2050_carboneutre_peaks,apply_postprocessing=True)
plot_sankey(results_peaks_2050_carboneutre)

Gurobi 12.0.3:

In [36]:
results_peaks_2050_carboneutre.variables['F_Mult_t']

                    F_Mult_t  Run
index0      index1
ACETIC_ACID 1            0.0    0
            2            0.0    0
            3            0.0    0
            4            0.0    0
            5            0.0    0
...                      ...  ...
XYLENE      10           0.0    0
            11           0.0    0
            12           0.0    0
            13           0.0    0
            14           0.0    0

[10892 rows x 2 columns]

In [119]:
df = results_peaks_2050_carboneutre.variables['F_Mult']

# Filtrer les lignes contenant "HP" (sensible à la casse)
df_filtre = df[df.index.str.contains('HP', na=False)]

print(df_filtre)

                       F_Mult  Run
index
CEMENT_PROD_HP       0.000000    0
DEC_HP_ELEC          0.001115    0
DEC_HP_ELEC_PEAK     0.001115    0
DEC_HP_ELEC_WINTER   0.001115    0
DEC_THHP_BIOGAS      0.000000    0
DEC_THHP_GAS         0.000000    0
DHN_HP_ELEC          0.000000    0
EHP_H2_GRID          0.855772    0
EHP_NG_GRID         36.332374    0
FOOD_PROD_HP         0.000000    0
HP_H2_GRID           0.855772    0
HP_NG_GRID          36.332374    0
HYDRO_GAS_CHP        0.000000    0
IND_HP_ELEC          0.000000    0
PAPER_MAKING_HP      0.000000    0
STEEL_MAKING_HP      0.000000    0

In [120]:
df = results_peaks_2050_carboneutre.parameters['f_max']
df_filtre = df[df.index.str.contains('HP', na=False)]

print(df_filtre)

                      f_max  Run
index
CEMENT_PROD_HP      10000.0    0
DEC_HP_ELEC         10000.0    0
DEC_HP_ELEC_PEAK    10000.0    0
DEC_HP_ELEC_WINTER  10000.0    0
DEC_THHP_BIOGAS         0.0    0
DEC_THHP_GAS            0.0    0
DHN_HP_ELEC         10000.0    0
EHP_H2_GRID         10000.0    0
EHP_NG_GRID         10000.0    0
FOOD_PROD_HP        10000.0    0
HP_H2_GRID          10000.0    0
HP_NG_GRID          10000.0    0
HYDRO_GAS_CHP       10000.0    0
IND_HP_ELEC             0.0    0
PAPER_MAKING_HP     10000.0    0
STEEL_MAKING_HP     10000.0    0

In [15]:
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_peaks_2050_carboneutre.pkl')
os.makedirs(output_dir, exist_ok=True)

# Sauvegarde
with open(output_path, 'wb') as f:
    pickle.dump(results_peaks_2050_carboneutre, f)

# 2050 - Avec pointe - Carboneutre - Plan HQ

In [122]:
from pathlib import Path

# 1. Définition des chemins absolus
_BASE_DIR = Path(r"C:\Users\julie\Desktop\EnergyScope-Quebec")
_MODEL_2050_DIR = _BASE_DIR / 'shared' / 'model'
_DATA_2050_DIR = _BASE_DIR / 'shared' / 'data'
_DATA_EUD_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'EUD'
_DATA_TECHS_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Techs'
_DATA_SHARES_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Shares'
_PROJECT_DIR = _BASE_DIR / 'projects' / 'peaks' / '02_Model'

# 2. Construction du modèle unique ordonné (2050 Carboneutre - Sans Pointes, Avec HP)
energyscope_2050_carboneutre_peaks_planHQ = Model([
    # --- 1. DÉCLARATIONS DES MODÈLES (Tous les .mod de base et extensions) ---
    ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
    ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
    ('mod', str(_PROJECT_DIR / 'peaks_extra.mod')),
    ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
    ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
    ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
    ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
    ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),

    # --- 2. AJOUTS HP, SPLIT IMPORTS,  (Via des commandes 'let') ---
    ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
    ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),

    ('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')),
    ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

    ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
    ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),
    ('mod', str(_PROJECT_DIR / 'plan_action_HQ_2035.mod')),

    # --- 3. Carboneutre ---
    ('dat', str(_PROJECT_DIR / 'carboneutre.dat')),

    # --- 4. Pointes ---
    ('dat', str(_PROJECT_DIR / 'peaks_2_2050.dat')),
    ('dat', str(_PROJECT_DIR / 'peaks_2050_cpt.dat')),
])

In [123]:
results_peaks_2050_carboneutre_planHQ = run_model(energyscope_2050_carboneutre_peaks_planHQ,apply_postprocessing=True)
plot_sankey(results_peaks_2050_carboneutre_planHQ)

Gurobi 12.0.3:

In [124]:
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_peaks_2050_carboneutre_planHQ.pkl')
os.makedirs(output_dir, exist_ok=True)

# Sauvegarde
with open(output_path, 'wb') as f:
    pickle.dump(results_peaks_2050_carboneutre_planHQ, f)

In [125]:
results_peaks_2050_carboneutre_planHQ

Result(constraints={}, parameters={'avail':                                 avail  Run
index
ACETIC_ACID                       inf    0
ACETONE                           inf    0
BENZENE                           inf    0
BIOMASS_AGRICULTURE_DEJECTION  4149.0    0
BIOMASS_AGRICULTURE_RESIDUAL   2293.0    0
...                               ...  ...
WASTE_BIO                         0.0    0
WASTE_FOS                         0.0    0
WET_BIOMASS                       0.0    0
WOOD                              0.0    0
XYLENE                            inf    0

[86 rows x 2 columns], 'bio_ratio':    bio_ratio  Run
0          0    0, 'c_inv':                              c_inv  Run
index
AFC                     629.639000    0
ALKALINE_ELECTROLYSIS  1274.606192    0
AL_MAKING                 0.000000    0
AL_MAKING_HR              0.000000    0
AN_DIG                 1807.811000    0
...                            ...  ...
TRUCK_SH_PROPANE_SD       0.000000    0
UNMINEABLE_COAL_SEAM      0.008000    0
WIND_OFFSHORE          3551.555199    0
WIND_ONSHORE           1791.957171    0
WOOD_METHANOL          2414.476867    0

[692 rows x 2 columns], 'c_maint':                           c_maint  Run
index
AFC                     12.590000    0
ALKALINE_ELECTROLYSIS   24.651516    0
AL_MAKING                0.000000    0
AL_MAKING_HR             0.000000    0
AN_DIG                 161.226000    0
...                           ...  ...
TRUCK_SH_PROPANE_SD      0.000000    0
UNMINEABLE_COAL_SEAM     0.000000    0
WIND_OFFSHORE          135.493080    0
WIND_ONSHORE            60.420601    0
WOOD_METHANOL          120.723867    0

[692 rows x 2 columns], 'c_op':                       c_op  Run
index0      index1
ACETIC_ACID 1       0.0723    0
            2       0.0723    0
            3       0.0723    0
            4       0.0723    0
            5       0.0723    0
...                    ...  ...
XYLENE      10      0.0812    0
            11      0.0812    0
            12      0.0812    0
            13      0.0000    0
            14      0.0000    0

[1204 rows x 2 columns], 'c_p':                         c_p  Run
index
AFC                    0.97    0
ALKALINE_ELECTROLYSIS  0.90    0
AL_MAKING              0.85    0
AL_MAKING_HR           0.85    0
AN_DIG                 1.00    0
...                     ...  ...
TRUCK_SH_PROPANE_SD    1.00    0
UNMINEABLE_COAL_SEAM   0.85    0
WIND_OFFSHORE          1.00    0
WIND_ONSHORE           1.00    0
WOOD_METHANOL          0.86    0

[692 rows x 2 columns], 'c_p_t':                       c_p_t  Run
index0        index1
AFC           1         1.0    0
              2         1.0    0
              3         1.0    0
              4         1.0    0
              5         1.0    0
...                     ...  ...
WOOD_METHANOL 10        1.0    0
              11        1.0    0
              12        1.0    0
              13        1.0    0
              14        1.0    0

[9604 rows x 2 columns], 'c_tax': Empty DataFrame
Columns: [c_tax, Run]
Index: [], 'c_tax_co2':    c_tax_co2  Run
0          0    0, 'c_tax_fuel':    c_tax_fuel  Run
0           0    0, 'c_tax_import': Empty DataFrame
Columns: [c_tax_import, Run]
Index: [], 'c_tax_res': Empty DataFrame
Columns: [c_tax_res, Run]
Index: [], 'co2_limit':    co2_limit  Run
0          0    0, 'co2_limit_max':    co2_limit_max  Run
0              0    0, 'cooling_month':     cooling_month  Run
1           0.000    0
2           0.000    0
3           0.000    0
4           0.000    0
5           0.058    0
6           0.203    0
7           0.484    0
8           0.246    0
9           0.009    0
10          0.000    0
11          0.000    0
12          0.000    0
13          0.000    0
14          0.000    0, 'cop_normal':    cop_normal  Run
0           3    0, 'cop_peak':    cop_peak  Run
0      1.15    0, 'cop_winter':    cop_winter  Run
0           2    0, 'e_density': Empty DataFrame
Columns: [e_density, Run]
Index: [], 'elec_export_month':     elec_export_month  Run
1            0.085934    0
2            0.081836    0
3            0.091120    0
4            0.074880    0
5            0.070870    0
6            0.085800    0
7            0.096990    0
8            0.099370    0
9            0.081780    0
10           0.067150    0
11           0.077970    0
12           0.085940    0
13           0.000116    0
14           0.000244    0, 'end_uses_demand_year':                             end_uses_demand_year  Run
index0      index1
ACETIC_ACID AGRICULTURE                      0.0    0
            EXPORT                           0.0    0
            HOUSEHOLDS                       0.0    0
            INDUSTRY                         0.0    0
            SERVICES                         0.0    0
...                                          ...  ...
STEEL       EXPORT                           0.0    0
            HOUSEHOLDS                       0.0    0
            INDUSTRY                         0.0    0
            SERVICES                         0.0    0
            TRANSPORTATION                   0.0    0

[210 rows x 2 columns], 'end_uses_input':                         end_uses_input  Run
index
ACETIC_ACID                   0.000000    0
ACETONE                       0.000000    0
ALUMINUM                      0.000000    0
BIO_JETFUEL                   0.000000    0
BIO_METHANOL                  0.000000    0
CEMENT                        0.000000    0
ELECTRICITY_EHV            8153.216673    0
ELECTRICITY_EHV_EXPORT    35556.000000    0
ELECTRICITY_HV            83946.406402    0
ELECTRICITY_LV            33995.663975    0
ELECTRICITY_MV            20141.195602    0
FOOD                          0.000000    0
HEAT_HIGH_T               87056.154908    0
HEAT_LOW_T_HW             19956.031506    0
HEAT_LOW_T_SC              7357.205441    0
HEAT_LOW_T_SH             95224.623347    0
JETFUEL                       0.000000    0
LIGHTING                  29065.043617    0
METHANOL                      0.000000    0
MOBILITY_FREIGHT_ELD     114381.818271    0
MOBILITY_FREIGHT_LD       22626.525339    0
MOBILITY_FREIGHT_MD       29451.914883    0
MOBILITY_FREIGHT_SD       12536.444649    0
MOBILITY_PASSENGER_ELD        0.000000    0
MOBILITY_PASSENGER_LD     61446.766651    0
MOBILITY_PASSENGER_MD     54825.051096    0
MOBILITY_PASSENGER_SD     62939.044515    0
PAPER                         0.000000    0
PE                            0.000000    0
PET                           0.000000    0
PHENOL                        0.000000    0
PP                            0.000000    0
PS                            0.000000    0
PVC                           0.000000    0
STEEL                         0.000000    0, 'f_grid_ext':              f_grid_ext  Run
EHP_H2_GRID    0.000000    0
EHP_NG_GRID    9.670442    0
EHV_GRID      35.948127    0
HP_H2_GRID     0.000000    0
HP_NG_GRID     9.670442    0
HV_GRID       30.680583    0
LP_H2_GRID     0.000000    0
LP_NG_GRID     4.986711    0
LV_GRID       21.794526    0
MP_H2_GRID     0.000000    0
MP_NG_GRID     9.653959    0
MV_GRID       23.895296    0, 'f_max':                            f_max  Run
index
AFC                    10000.000    0
ALKALINE_ELECTROLYSIS  10000.000    0
AL_MAKING              10000.000    0
AL_MAKING_HR           10000.000    0
AN_DIG                 10000.000    0
...                          ...  ...
TRUCK_SH_PROPANE_SD    10000.000    0
UNMINEABLE_COAL_SEAM       0.000    0
WIND_OFFSHORE           2179.000    0
WIND_ONSHORE            3984.322    0
WOOD_METHANOL          10000.000    0

[692 rows x 2 columns], 'f_min':                        f_min  Run
index
AFC                      0.0    0
ALKALINE_ELECTROLYSIS    0.0    0
AL_MAKING                0.0    0
AL_MAKING_HR             0.0    0
AN_DIG                   0.0    0
...                      ...  ...
TRUCK_SH_PROPANE_SD      0.0    0
UNMINEABLE_COAL_SEAM     0.0    0
WIND_OFFSHORE            0.0    0
WIND_ONSHORE             0.0    0
WOOD_METHANOL            0.0    0

[692 rows x 2 columns], 'f_mult_max':                      f_mult_max  Run
index0      index1
ACETIC_ACID 1       100000000.0    0
            2       100000000.0    0
            3       100000000.0    0
            4       100000000.0    0
            5       100000000.0    0
...                         ...  ...
XYLENE      10      100000000.0    0
            11      100000000.0    0
            12      100000000.0    0
            13      100000000.0    0
            14      100000000.0    0

[1204 rows x 2 columns], 'fmax_perc':                            fmax_perc  Run
index
AFC                                1    0
AL_MAKING                          1    0
AL_MAKING_HR                       1    0
AN_DIG_SI                          1    0
BIOMETHANE_TO_BIOMETHANOL          1    0
...                              ...  ...
TRUCK_SH_PROPANE_MD                1    0
TRUCK_SH_PROPANE_SD                1    0
WIND_OFFSHORE                      1    0
WIND_ONSHORE                       1    0
WOOD_METHANOL                      1    0

[423 rows x 2 columns], 'fmax_perc_mob':                           fmax_perc_mob  Run
index
BULK_CARRIER_BIOMEOH_ELD              1    0
BULK_CARRIER_BIO_ELD                  1    0
BULK_CARRIER_ELD                      1    0
BULK_CARRIER_MEOH_ELD                 1    0
BUS_BIODIESEL_B100_SD                 1    0
...                                 ...  ...
TRUCK_SH_GASOLINE_SD                  1    0
TRUCK_SH_HY_DIESEL_MD                 1    0
TRUCK_SH_HY_DIESEL_SD                 1    0
TRUCK_SH_PROPANE_MD                   1    0
TRUCK_SH_PROPANE_SD                   1    0

[307 rows x 2 columns], 'fmin_perc':                            fmin_perc  Run
index
AFC                                0    0
AL_MAKING                          0    0
AL_MAKING_HR                       0    0
AN_DIG_SI                          0    0
BIOMETHANE_TO_BIOMETHANOL          0    0
...                              ...  ...
TRUCK_SH_PROPANE_MD                0    0
TRUCK_SH_PROPANE_SD                0    0
WIND_OFFSHORE                      0    0
WIND_ONSHORE                       0    0
WOOD_METHANOL                      0    0

[423 rows x 2 columns], 'fmin_perc_mob':                           fmin_perc_mob  Run
index
BULK_CARRIER_BIOMEOH_ELD              0    0
BULK_CARRIER_BIO_ELD                  0    0
BULK_CARRIER_ELD                      0    0
BULK_CARRIER_MEOH_ELD                 0    0
BUS_BIODIESEL_B100_SD                 0    0
...                                 ...  ...
TRUCK_SH_GASOLINE_SD                  0    0
TRUCK_SH_HY_DIESEL_MD                 0    0
TRUCK_SH_HY_DIESEL_SD                 0    0
TRUCK_SH_PROPANE_MD                   0    0
TRUCK_SH_PROPANE_SD                   0    0

[307 rows x 2 columns], 'gwp_constr':                        gwp_constr  Run
index
AFC                             0    0
ALKALINE_ELECTROLYSIS           0    0
AL_MAKING                       0    0
AL_MAKING_HR                    0    0
AN_DIG                          0    0
...                           ...  ...
TRUCK_SH_PROPANE_SD             0    0
UNMINEABLE_COAL_SEAM            0    0
WIND_OFFSHORE                   0    0
WIND_ONSHORE                    0    0
WOOD_METHANOL                   0    0

[692 rows x 2 columns], 'gwp_e':                     gwp_e  Run
index0      index1
ACETIC_ACID 1           0    0
            2           0    0
            3           0    0
            4           0    0
            5           0    0
...                   ...  ...
XYLENE      10          0    0
            11          0    0
            12          0    0
            13          0    0
            14          0    0

[1204 rows x 2 columns], 'heating_month':     heating_month  Run
1        0.197976    0
2        0.164593    0
3        0.142100    0
4        0.031900    0
5        0.000000    0
6        0.000000    0
7        0.000000    0
8        0.000000    0
9        0.014700    0
10       0.089800    0
11       0.138300    0
12       0.219400    0
13       0.000424    0
14       0.000807    0, 'i_rate':    i_rate  Run
0    0.04    0, 'k_security':              k_security  Run
EHP_H2_GRID           6    0
EHP_NG_GRID           6    0
EHV_GRID              6    0
HP_H2_GRID            6    0
HP_NG_GRID            6    0
HV_GRID               6    0
LP_H2_GRID            6    0
LP_NG_GRID            6    0
LV_GRID               6    0
MP_H2_GRID            6    0
MP_NG_GRID            6    0
MV_GRID               6    0, 'l_grid_ext':              l_grid_ext  Run
EHP_H2_GRID         789    0
EHP_NG_GRID         789    0
EHV_GRID          12581    0
HP_H2_GRID           76    0
HP_NG_GRID           76    0
HV_GRID           22341    0
LP_H2_GRID         7560    0
LP_NG_GRID         7560    0
LV_GRID          108096    0
MP_H2_GRID         1966    0
MP_NG_GRID         1966    0
MV_GRID          120472    0, 'l_grid_ref':              l_grid_ref  Run
EHP_H2_GRID   39.450000    0
EHP_NG_GRID   39.450000    0
EHV_GRID     285.931818    0
HP_H2_GRID     0.655172    0
HP_NG_GRID     0.655172    0
HV_GRID       27.996241    0
LP_H2_GRID     0.017182    0
LP_NG_GRID     0.017182    0
LV_GRID        0.023757    0
MP_H2_GRID     0.964198    0
MP_NG_GRID     0.964198    0
MV_GRID       37.647500    0, 'layers_in_out':                                            layers_in_out  Run
index0      index1
ACETIC_ACID ACETIC_ACID                              1.0    0
            ACETONE                                  0.0    0
            ALUMINUM                                 0.0    0
            BENZENE                                  0.0    0
            BIOMASS_AGRICULTURE_DEJECTION            0.0    0
...                                                  ...  ...
XYLENE      WASTE_BIO                                0.0    0
            WASTE_FOS                                0.0    0
            WET_BIOMASS                              0.0    0
            WOOD                                     0.0    0
            XYLENE                                   1.0    0

[75969 rows x 2 columns], 'lifetime':                        lifetime  Run
index
AFC                        35.0    0
ALKALINE_ELECTROLYSIS      10.0    0
AL_MAKING                  25.0    0
AL_MAKING_HR               25.0    0
AN_DIG                     25.0    0
...                         ...  ...
TRUCK_SH_PROPANE_SD        15.0    0
UNMINEABLE_COAL_SEAM       25.0    0
WIND_OFFSHORE              25.0    0
WIND_ONSHORE               25.0    0
WOOD_METHANOL              20.0    0

[692 rows x 2 columns], 'lighting_month':     lighting_month  Run
1         0.123833    0
2         0.101696    0
3         0.091800    0
4         0.070800    0
5         0.058800    0
6         0.043800    0
7         0.040800    0
8         0.039800    0
9         0.067800    0
10        0.104800    0
11        0.123800    0
12        0.131800    0
13        0.000167    0
14        0.000304    0, 'loss_coeff':                   loss_coeff  Run
index
ACETIC_ACID         0.000000    0
ACETONE             0.000000    0
ALUMINUM            0.000000    0
BIO_METHANOL        0.000000    0
CEMENT              0.000000    0
ELECTRICITY_EHV     0.030900    0
ELECTRICITY_HV      0.000145    0
ELECTRICITY_LV      0.000491    0
ELECTRICITY_MV      0.001460    0
FOOD                0.000000    0
HEAT_HIGH_T         0.000000    0
HEAT_LOW_T_DECEN    0.000000    0
HEAT_LOW_T_DHN      0.050000    0
METHANOL            0.000000    0
MOB_FREIGHT_ELD     0.000000    0
MOB_FREIGHT_LD      0.000000    0
MOB_FREIGHT_MD      0.000000    0
MOB_FREIGHT_SD      0.000000    0
MOB_PRIVATE_ELD     0.000000    0
MOB_PRIVATE_LD      0.000000    0
MOB_PRIVATE_MD      0.000000    0
MOB_PRIVATE_SD      0.000000    0
MOB_PUBLIC_ELD      0.000000    0
MOB_PUBLIC_LD       0.000000    0
MOB_PUBLIC_MD       0.000000    0
MOB_PUBLIC_SD       0.000000    0
PAPER               0.000000    0
PE                  0.000000    0
PET                 0.000000    0
PHENOL              0.000000    0
PP                  0.000000    0
PS                  0.000000    0
PVC                 0.000000    0
STEEL               0.000000    0, 'max_hydro_utilization_rate':    max_hydro_utilization_rate  Run
0                       0.705    0, 'n_stations':              n_stations  Run
EHP_H2_GRID          20    0
EHP_NG_GRID          20    0
EHV_GRID             44    0
HP_H2_GRID          116    0
HP_NG_GRID          116    0
HV_GRID             798    0
LP_H2_GRID       440000    0
LP_NG_GRID       440000    0
LV_GRID         4550000    0
MP_H2_GRID         2039    0
MP_NG_GRID         2039    0
MV_GRID            3200    0, 'out_max':                        out_max  Run
index
AFC                        inf    0
ALKALINE_ELECTROLYSIS      inf    0
AL_MAKING                  inf    0
AL_MAKING_HR               inf    0
AN_DIG                     inf    0
...                        ...  ...
TRUCK_SH_PROPANE_SD        inf    0
UNMINEABLE_COAL_SEAM       inf    0
WIND_OFFSHORE              inf    0
WIND_ONSHORE               inf    0
WOOD_METHANOL              inf    0

[689 rows x 2 columns], 'out_min':                        out_min  Run
index
AFC                          0    0
ALKALINE_ELECTROLYSIS        0    0
AL_MAKING                    0    0
AL_MAKING_HR                 0    0
AN_DIG                       0    0
...                        ...  ...
TRUCK_SH_PROPANE_SD          0    0
UNMINEABLE_COAL_SEAM         0    0
WIND_OFFSHORE                0    0
WIND_ONSHORE                 0    0
WOOD_METHANOL                0    0

[689 rows x 2 columns], 'peak_dhn_factor':    peak_dhn_factor  Run
0                1    0, 'ref_size':                            ref_size  Run
index
ALKALINE_ELECTROLYSIS         0.001    0
AL_MAKING                    10.000    0
AL_MAKING_HR                 10.000    0
AN_DIG_SI                     0.005    0
BIOETHANOL_TO_BIOJETFUELS     0.115    0
...                             ...  ...
TRAIN_SNG                     0.053    0
TRAMWAY                       0.004    0
UNMINEABLE_COAL_SEAM          0.001    0
WIND_ONSHORE                  0.003    0
WOOD_METHANOL                 0.001    0

[235 rows x 2 columns], 'renew':    renew  Run
0      0    0, 'reno_max':    reno_max  Run
0     10000    0, 'reno_min':    reno_min  Run
0         0    0, 'reno_share_max':    reno_share_max  Run
0             0.5    0, 'reno_share_min':    reno_share_min  Run
0               0    0, 'share_freight_air_max_eld':    share_freight_air_max_eld  Run
0                     0.0063    0, 'share_freight_air_min_eld':    share_freight_air_min_eld  Run
0                     0.0063    0, 'share_freight_maritime_bulk_carrier':    share_freight_maritime_bulk_carrier  Run
0                                 0.56    0, 'share_freight_maritime_container':    share_freight_maritime_container  Run
0                              0.17    0, 'share_freight_maritime_max_eld':    share_freight_maritime_max_eld  Run
0                          0.5879    0, 'share_freight_maritime_min_eld':    share_freight_maritime_min_eld  Run
0                          0.5879    0, 'share_freight_maritime_oil_tanker':    share_freight_maritime_oil_tanker  Run
0                               0.26    0, 'share_freight_rail_max_eld':    share_freight_rail_max_eld  Run
0                      0.2209    0, 'share_freight_rail_max_ld':    share_freight_rail_max_ld  Run
0                     0.3723    0, 'share_freight_rail_min_eld':    share_freight_rail_min_eld  Run
0                      0.2209    0, 'share_freight_rail_min_ld':    share_freight_rail_min_ld  Run
0                     0.3723    0, 'share_heat_dhn_max':    share_heat_dhn_max  Run
0                0.05    0, 'share_heat_dhn_min':    share_heat_dhn_min  Run
0                   0    0, 'share_mobility_public_max_eld':    share_mobility_public_max_eld  Run

In [126]:
results_peaks_2050_carboneutre_planHQ.variables['F_Mult'].loc[['DEC_HP_ELEC']]

               F_Mult  Run
index
DEC_HP_ELEC  0.001119    0

In [127]:
df = results_peaks_2050_carboneutre_planHQ.parameters['layers_in_out'].loc['DEC_HP_ELEC_PEAK']
df_filtre = df[df['layers_in_out'] != 0]
df_filtre

                  layers_in_out  Run
index1
ELECTRICITY_LV        -0.869565    0
HEAT_LOW_T_DECEN       1.000000    0

In [128]:
df = results_peaks_2050_carboneutre_planHQ.variables['F_Mult']
df

                          F_Mult  Run
index
AFC                     0.036685    0
ALKALINE_ELECTROLYSIS   0.000000    0
AL_MAKING               0.000000    0
AL_MAKING_HR            0.000000    0
AN_DIG                  0.000000    0
...                          ...  ...
TRUCK_SH_PROPANE_SD     0.000000    0
UNMINEABLE_COAL_SEAM    0.000000    0
WIND_OFFSHORE           0.000000    0
WIND_ONSHORE           10.756553    0
WOOD_METHANOL           0.000000    0

[692 rows x 2 columns]

In [129]:
df = results_peaks_2050_carboneutre_planHQ.variables['F_Mult']

# Filtrer les lignes contenant "HP" (sensible à la casse)
df_filtre = df[df.index.str.contains('HP', na=False)]

print(df_filtre)

                       F_Mult  Run
index
CEMENT_PROD_HP       0.000000    0
DEC_HP_ELEC          0.001119    0
DEC_HP_ELEC_PEAK     0.001119    0
DEC_HP_ELEC_WINTER   0.001119    0
DEC_THHP_BIOGAS      0.000000    0
DEC_THHP_GAS         0.000000    0
DHN_HP_ELEC          0.000000    0
EHP_H2_GRID          0.855773    0
EHP_NG_GRID         36.332374    0
FOOD_PROD_HP         0.000000    0
HP_H2_GRID           0.855773    0
HP_NG_GRID          36.332374    0
HYDRO_GAS_CHP        0.000000    0
IND_HP_ELEC          0.000000    0
PAPER_MAKING_HP      0.000000    0
STEEL_MAKING_HP      0.000000    0

# 2050 - Sensibilité - Capture carbone

In [155]:
results_peaks_2050_carboneutre_planHQ.variables['Annual_Prod'].loc['CARBON_CAPTURE_MEMBRANES']

Annual_Prod    34354.502718
Run                0.000000
Name: CARBON_CAPTURE_MEMBRANES, dtype: float64

In [136]:
# 1. Définition des chemins absolus
_BASE_DIR = Path(r"C:\Users\julie\Desktop\EnergyScope-Quebec")
_MODEL_2050_DIR = _BASE_DIR / 'shared' / 'model'
_DATA_2050_DIR = _BASE_DIR / 'shared' / 'data'
_DATA_EUD_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'EUD'
_DATA_TECHS_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Techs'
_DATA_SHARES_2050_DIR = _BASE_DIR / 'shared' / 'data' / 'Shares'
_PROJECT_DIR = _BASE_DIR / 'projects' / 'peaks' / '02_Model'

In [151]:
import pandas as pd
import numpy as np

# 1. Définir les valeurs de f_max à tester (de 0 à 25 par tranche de 5)
f_max_values = np.arange(0, 37.5, 2.5).tolist()# Génère : [0.0, 2.5, 5.0, ... , 32.5, 35.0]

# 2. Initialiser le dictionnaire global qui contiendra TOUT
tous_les_resultats = {}

# Chemin vers ton fichier d'analyse de sensibilité
as_file_path = _PROJECT_DIR / 'AS_f_max_membrane.dat'

print("Début de l'analyse de sensibilité (Option 1)...")

# 3. Boucle sur chaque valeur de f_max
for val in f_max_values:
    print(f"\n--- Exécution pour f_max = {val} ---")

    # ÉTAPE 1 : Modifier dynamiquement le fichier .dat
    with open(as_file_path, 'w') as f:
        f.write(f"let f_max['YEAR_2050','CARBON_CAPTURE_MEMBRANES'] := {val} ;\n")

    # ÉTAPE 2 : Recréer le modèle
    energyscope_2050_carboneutre_peaks_AS_CC = Model([
        ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
        ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
        ('mod', str(_PROJECT_DIR / 'peaks_extra.mod')),
        ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
        ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
        ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
        ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
        ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),

        ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
        ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),

        ('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')),
        ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
        ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

        ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
        ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),

        ('dat', str(_PROJECT_DIR / 'carboneutre.dat')),

        ('dat', str(_PROJECT_DIR / 'peaks_2_2050.dat')),
        ('dat', str(_PROJECT_DIR / 'peaks_2050_cpt.dat')),

        # Fichier d'analyse de sensibilité mis à jour
        ('dat', str(as_file_path)),
    ])

    # ÉTAPE 3 : Run le modèle
    results_run = run_model(energyscope_2050_carboneutre_peaks_AS_CC, apply_postprocessing=True)

    # ÉTAPE 4 : Stocker l'intégralité de l'objet de résultats dans le dictionnaire
    # On crée une clé unique par scénario (ex: 'f_max_0', 'f_max_5')
    nom_scenario = f"f_max_{val}"
    tous_les_resultats[nom_scenario] = results_run

print("\nAnalyse de sensibilité terminée avec succès !")


# ==============================================================================
# EXEMPLE D'UTILISATION APRÈS LA BOUCLE
# ==============================================================================
# Maintenant que tout est en mémoire dans `tous_les_resultats`, tu peux reconstruire
# ton tableau de F_Mult à tout moment sans relancer le solveur :

f_mult_post_analysis = {}

for nom_scenario, res in tous_les_resultats.items():
    # Extraire F_Mult de l'objet sauvegardé
    df_f_mult = res.variables['F_Mult'].copy()
    df_f_mult = df_f_mult.drop(columns=['Run'], errors='ignore')

    # Stocker la colonne de données
    f_mult_post_analysis[nom_scenario] = df_f_mult.iloc[:, 0]

# Créer le DataFrame final
df_AS_F_Mult = pd.DataFrame(f_mult_post_analysis)

Début de l'analyse de sensibilité (Option 1)...

--- Exécution pour f_max = 0.0 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 2.5 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 5.0 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 7.5 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 10.0 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 12.5 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 15.0 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 17.5 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 20.0 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 22.5 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 25.0 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 27.5 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 30.0 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 32.5 ---
Gurobi 12.0.3:
--- Exécution pour f_max = 35.0 ---
Gurobi 12.0.3:
Analyse de sensibilité terminée avec succès !

In [152]:
# 1. Définir le dossier et le chemin du fichier de sortie
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_peaks_2050_carboneutre_AS_membrane.pkl')

# 2. Créer le dossier s'il n'existe pas
os.makedirs(output_dir, exist_ok=True)

# 3. Écriture du fichier binaire .pkl
with open(output_path, 'wb') as f:
    # On sauvegarde l'objet 'tous_les_resultats' qui contient TOUTES les itérations
    pickle.dump(tous_les_resultats, f)

In [162]:
import pandas as pd
import numpy as np
import pickle
import os

# 1. Définir les valeurs de limite à tester (de 0 à 40 par tranche de 2.5)
# On pousse à 42.5 pour inclure 40.0 dans la liste
limites_capture = np.arange(0, 42.5, 10).tolist()

# 2. Initialiser le dictionnaire global qui contiendra TOUT
tous_les_resultats_capture = {}

# Chemins vers tes fichiers d'analyse de sensibilité
as_mod_path = _PROJECT_DIR / 'AS_capture_limite.mod'
as_dat_path = _PROJECT_DIR / 'AS_capture_limite.dat'

print(f"Début de l'analyse de sensibilité sur la capture ({len(limites_capture)} itérations)...")

# 3. Boucle sur chaque valeur de la limite
for val in limites_capture:
    print(f"\n--- Exécution pour Limite Capture Totale = {val} ---")

    # ÉTAPE 1 : Modifier dynamiquement le fichier .dat avec la nouvelle limite
    with open(as_dat_path, 'w') as f:
        f.write(f"let max_capture_totale := {val} ;\n")

    # ÉTAPE 2 : Recréer le modèle (en incluant le .mod ET le .dat de l'analyse de sensibilité)
    energyscope_2050_carboneutre_peaks_AS_CC = Model([
        ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
        ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
        ('mod', str(_PROJECT_DIR / 'peaks_extra.mod')),
        ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
        ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
        ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
        ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
        ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),

        ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
        ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),

        ('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')),
        ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
        ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

        ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
        ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),

        ('dat', str(_PROJECT_DIR / 'carboneutre.dat')),

        ('dat', str(_PROJECT_DIR / 'peaks_2_2050.dat')),
        ('dat', str(_PROJECT_DIR / 'peaks_2050_cpt.dat')),

        # --- AJOUTS POUR L'ANALYSE DE SENSIBILITÉ ---
        ('mod', str(as_mod_path)), # Contient la définition de la contrainte et du paramètre
        ('dat', str(as_dat_path)), # Contient la valeur changeante (let max_capture_totale := ...)
    ])

    # ÉTAPE 3 : Run le modèle
    results_run = run_model(energyscope_2050_carboneutre_peaks_AS_CC, apply_postprocessing=True)

    # ÉTAPE 4 : Stocker l'objet dans le dictionnaire
    nom_scenario = f"limite_{val}"
    tous_les_resultats_capture[nom_scenario] = results_run

print("\nAnalyse de sensibilité sur la capture terminée avec succès !")

# ==============================================================================
# SAUVEGARDE PICKLE
# ==============================================================================
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_peaks_2050_carboneutre_AS_somme_capture.pkl')
os.makedirs(output_dir, exist_ok=True)

print(f"Sauvegarde du dictionnaire dans : {output_path}...")
with open(output_path, 'wb') as f:
    pickle.dump(tous_les_resultats_capture, f)
print("Sauvegarde réussie !")

Début de l'analyse de sensibilité sur la capture (5 itérations)...

--- Exécution pour Limite Capture Totale = 0.0 ---
Gurobi 12.0.3:
--- Exécution pour Limite Capture Totale = 10.0 ---
Gurobi 12.0.3:
--- Exécution pour Limite Capture Totale = 20.0 ---
Gurobi 12.0.3:
--- Exécution pour Limite Capture Totale = 30.0 ---
Gurobi 12.0.3:
--- Exécution pour Limite Capture Totale = 40.0 ---
Gurobi 12.0.3:
Analyse de sensibilité sur la capture terminée avec succès !
Sauvegarde du dictionnaire dans : ../03_Results\results_peaks_2050_carboneutre_AS_somme_capture.pkl...
Sauvegarde réussie !

In [168]:
# Sélectionner et afficher le Sankey pour le scénario limite_10.0
plot_sankey(tous_les_resultats_capture['limite_40.0'])

In [173]:
TECHS_CAPTURE = [
    # Technologies of CC
    'DAC_HT', 'DAC_LT', 'CARBON_CAPTURE', 'CARBON_CAPTURE_AMINES', 'CARBON_CAPTURE_MEMBRANES', 'CARBON_CAPTURE_MOF',

    # Technologies of CCS
    'EOR', 'DOGR', 'UNMINEABLE_COAL_SEAM', 'DEEP_SALINE', 'MINES_STORAGE', 'CARBON_MINERALIZATION', 'CARBON_TRANSPORT_INJECTION',

    # Energy Technologies with CC
    'ATR_CCS', 'BIOGAS_ATR_CCS', 'SMR_CCS', 'BIOGAS_SMR_CCS', 'BIOMASS_GAS_EF_H2_CCS', 'BIOMASS_GAS_FB_H2_CCS',
    'COAL_GAS_H2_CCS', 'COAL_GAS_H2_ADV_CCS', 'CCGT_CC', 'CCGT_BIOGAS_CC', 'COAL_IGCC_CC', 'COAL_US_CC',
    'DHN_COGEN_WASTE_CC', 'H2_NG_CCGT_CCS', 'H2_SNG_CCGT_CCS', 'IND_BOILER_WASTE_CC', 'IND_COGEN_WASTE_CC'
]
results_peaks_2050_carboneutre.variables['Annual_Prod'].loc[TECHS_CAPTURE]

                             Annual_Prod  Run
index
DAC_HT                          0.000000    0
DAC_LT                          0.000000    0
CARBON_CAPTURE                  0.000000    0
CARBON_CAPTURE_AMINES           0.000000    0
CARBON_CAPTURE_MEMBRANES    34354.502718    0
CARBON_CAPTURE_MOF              0.000000    0
EOR                             0.000000    0
DOGR                            0.000000    0
UNMINEABLE_COAL_SEAM            0.000000    0
DEEP_SALINE                     0.000000    0
MINES_STORAGE                   0.000000    0
CARBON_MINERALIZATION       16861.764934    0
CARBON_TRANSPORT_INJECTION  15900.000000    0
ATR_CCS                         0.000000    0
BIOGAS_ATR_CCS                  0.000000    0
SMR_CCS                         0.000000    0
BIOGAS_SMR_CCS                  0.000000    0
BIOMASS_GAS_EF_H2_CCS           0.000000    0
BIOMASS_GAS_FB_H2_CCS           0.000000    0
COAL_GAS_H2_CCS                 0.000000    0
COAL_GAS_H2_ADV_CCS             0.000000    0
CCGT_CC                         0.000000    0
CCGT_BIOGAS_CC                  0.000000    0
COAL_IGCC_CC                    0.000000    0
COAL_US_CC                      0.000000    0
DHN_COGEN_WASTE_CC              0.000000    0
H2_NG_CCGT_CCS                  0.000000    0
H2_SNG_CCGT_CCS                 0.000000    0
IND_BOILER_WASTE_CC             0.000000    0
IND_COGEN_WASTE_CC              0.000000    0

In [130]:
results_wo_peaks_2050_carboneutre.variables['F_Mult'].loc['CARBON_CAPTURE_MEMBRANES']

F_Mult    4.476917
Run       0.000000
Name: CARBON_CAPTURE_MEMBRANES, dtype: float64

In [131]:
test_sens = results_peaks_2050_carboneutre

In [135]:
test_sens.variables['F_Mult'].loc['CARBON_CAPTURE_MEMBRANES']

F_Mult    4.61382
Run       0.00000
Name: CARBON_CAPTURE_MEMBRANES, dtype: float64

# 2050 - Sensibilité - Cout GN

In [153]:
import pandas as pd
import numpy as np
import pickle
import os

# 1. Définir les facteurs multiplicateurs (de 0.5 à 2.0 par pas de 0.25)
facteurs = np.arange(0.5, 2.25, 0.25).tolist()

# Prix de base d'importation du gaz
prix_base_gaz = 0.018743533792940855

# 2. Initialiser le dictionnaire global qui contiendra TOUT
tous_les_resultats_gaz = {}

# Chemin vers le fichier d'analyse de sensibilité pour le gaz
as_file_path = _PROJECT_DIR / 'AS_co_gaz.dat'

print(f"Début de l'analyse de sensibilité sur le prix du gaz ({len(facteurs)} itérations)...")

# 3. Boucle sur chaque facteur multiplicateur
for fac in facteurs:
    prix_calcule = prix_base_gaz * fac

    # Formatage propre du nom pour l'affichage et la clé
    if fac == 0.5:
        nom_scenario = "gaz_divise_par_2"
    elif fac == 2.0:
        nom_scenario = "gaz_multiplie_par_2"
    elif fac == 1.0:
        nom_scenario = "gaz_prix_de_base"
    else:
        nom_scenario = f"gaz_facteur_{fac:.2f}"

    print(f"\n--- Exécution pour {nom_scenario} (Prix: {prix_calcule:.6f}) ---")

    # ÉTAPE 1 : Modifier le fichier .dat pour les 14 périodes (1 à 14 inclus)
    with open(as_file_path, 'w') as f:
        for periode in range(1, 15):
            f.write(f"let c_op['YEAR_2050','NG_EHP',{periode}] := {prix_calcule} ;\n")

    # ÉTAPE 2 : Recréer le modèle
    energyscope_2050_carboneutre_peaks_AS_CC = Model([
        ('mod', str(_MODEL_2050_DIR / 'QC_es_main.mod')),
        ('mod', str(_MODEL_2050_DIR / 'QC_objective_function.mod')),
        ('mod', str(_PROJECT_DIR / 'peaks_extra.mod')),
        ('dat', str(_DATA_2050_DIR / 'QC_set_snapshot.dat')),
        ('dat', str(_DATA_2050_DIR / 'QC_data.dat')),
        ('dat', str(_DATA_EUD_2050_DIR / 'QC_eud_2050.dat')),
        ('dat', str(_DATA_SHARES_2050_DIR / 'QC_shares_2050.dat')),
        ('dat', str(_DATA_TECHS_2050_DIR / 'QC_techs_2050.dat')),

        ('mod', str(_PROJECT_DIR / 'HP_Winter.mod')),
        ('dat', str(_PROJECT_DIR / 'HP_Winter.dat')),

        ('mod', str(_PROJECT_DIR / 'Hydro_limit_annual.mod')),
        ('mod', str(_PROJECT_DIR / 'imports_split_2050.mod')),
        ('dat', str(_PROJECT_DIR / 'imports_split_2050.dat')),

        ('mod', str(_PROJECT_DIR / 'realisme_2050.mod')),
        ('dat', str(_PROJECT_DIR / 'realisme_2050.dat')),

        ('dat', str(_PROJECT_DIR / 'carboneutre.dat')),

        ('dat', str(_PROJECT_DIR / 'peaks_2_2050.dat')),
        ('dat', str(_PROJECT_DIR / 'peaks_2050_cpt.dat')),

        # Fichier de sensibilité mis à jour
        ('dat', str(as_file_path)),
    ])

    # ÉTAPE 3 : Run le modèle
    results_run = run_model(energyscope_2050_carboneutre_peaks_AS_CC, apply_postprocessing=True)

    # ÉTAPE 4 : Stocker l'objet dans le dictionnaire
    tous_les_resultats_gaz[nom_scenario] = results_run

print("\nAnalyse de sensibilité sur le gaz terminée avec succès !")

# ==============================================================================
# SAUVEGARDE AUTOMATIQUE (PICKLE)
# ==============================================================================
output_dir = '../03_Results'
output_path = os.path.join(output_dir, 'results_peaks_2050_carboneutre_AS_prix_gaz.pkl')
os.makedirs(output_dir, exist_ok=True)

print(f"Sauvegarde du dictionnaire dans : {output_path}...")
with open(output_path, 'wb') as f:
    pickle.dump(tous_les_resultats_gaz, f)
print("Sauvegarde réussie !")

Début de l'analyse de sensibilité sur le prix du gaz (7 itérations)...

--- Exécution pour gaz_divise_par_2 (Prix: 0.009372) ---
Gurobi 12.0.3:
--- Exécution pour gaz_facteur_0.75 (Prix: 0.014058) ---
Gurobi 12.0.3:
--- Exécution pour gaz_prix_de_base (Prix: 0.018744) ---
Gurobi 12.0.3:
--- Exécution pour gaz_facteur_1.25 (Prix: 0.023429) ---
Gurobi 12.0.3:
--- Exécution pour gaz_facteur_1.50 (Prix: 0.028115) ---
Gurobi 12.0.3:
--- Exécution pour gaz_facteur_1.75 (Prix: 0.032801) ---
Gurobi 12.0.3:
--- Exécution pour gaz_multiplie_par_2 (Prix: 0.037487) ---
Gurobi 12.0.3:
Analyse de sensibilité sur le gaz terminée avec succès !
Sauvegarde du dictionnaire dans : ../03_Results\results_peaks_2050_carboneutre_AS_prix_gaz.pkl...
Sauvegarde réussie !